runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  GOOGLE_CLOUD_PROJECT: "your-project-id"
  STORAGE_BUCKET: "eth-investment-data"
  NOTIFICATION_TOPIC: "eth-investment-notifications"
  SECRET_KEY: "change-this-to-a-secure-secret-key-in-production"

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
